
//EXTRA
export const GET_SINGLE_SUBJECT = 'GET_SINGLE_SUBJECT';
export const GET_SINGLE_CHAPTER = 'GET_SINGLE_CHAPTER';
export const SET_LOADING = 'SET_LOADING';
export const SET_IMPORT_LOADING = 'SET_IMPORT_LOADING';
export const REMOVE_LOADING = 'REMOVE_LOADING';
export const CHANGE_THEME_TO_DARK = 'CHANGE_THEME_TO_DARK'
export const CHANGE_THEME_TO_LIGHT = 'CHANGE_THEME_TO_LIGHT'


//ADD
export const ADD_SUBJECT = 'ADD_SUBJECT';
export const ADD_NOTES_TO_UNCATAGORISED = 'ADD_NOTES_TO_UNCATAGORISED';
export const ADD_PDF_TO_UNCATAGORISED = 'ADD_PDF_TO_UNCATAGORISED';

export const ADD_CHAPTER = 'ADD_CHAPTER';
export const ADD_NOTES_TO_UNCATAGORISED_IN_CHAPTER = 'ADD_NOTES_TO_UNCATAGORISED_IN_CHAPTER';
export const ADD_PDF_TO_UNCATAGORISED_IN_CHAPTER = 'ADD_PDF_TO_UNCATAGORISED_IN_CHAPTER';
export const ADD_NOTES_IN_CHAPTER = 'ADD_NOTES_IN_CHAPTER';
export const ADD_PDF_IN_CHAPTER = 'ADD_PDF_IN_CHAPTER';


//DELETE
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const DELETE_CHAPTER = 'DELETE_CHAPTER';
export const DELETE_PDF_FROM_UNCATAGORISED = 'DELETE_PDF_FROM_UNCATAGORISED';
export const DELETE_NOTES_FROM_UNCATAGORISED = 'DELETE_NOTES_FROM_UNCATAGORISED';
export const DELETE_PDF_FROM_UNCATAGORISED_IN_CHAPTER = 'DELETE_PDF_FROM_UNCATAGORISED_IN_CHAPTER';
export const DELETE_NOTES_FROM_UNCATAGORISED_IN_CHAPTER = 'DELETE_NOTES_FROM_UNCATAGORISED_IN_CHAPTER';
export const DELETE_NOTES_IN_CHAPTER = 'DELETE_NOTES_IN_CHAPTER';
export const DELETE_PDF_IN_CHAPTER = 'DELETE_PDF_IN_CHAPTER';



//EDIT
export const EDIT_SUBJECT = 'EDIT_SUBJECT';
export const EDIT_CHAPTER = 'EDIT_CHAPTER';


//Add show time
export const DELETE_SUBJECT_AD_EXPIRATION = 'DELETE_SUBJECT_AD_EXPIRATION';
export const EDIT_CHAPTER_AD_EXPIRATION = 'EDIT_CHAPTER_AD_EXPIRATION';
export const ADD_NOTES_TOUNCATAGORISED_AD_EXPIRATION = 'ADD_NOTES_TOUNCATAGORISED_AD_EXPIRATION'
export const ADD_PDF_TOUNCATAGORISED_AD_EXPIRATION = 'ADD_PDF_TOUNCATAGORISED_AD_EXPIRATION'
export const ADD_NOTES_TOUNCATAGORISED_IN_SUBJECT_AD_EXPIRATION = 'ADD_NOTES_TOUNCATAGORISED_IN_SUBJECT_AD_EXPIRATION'
export const DELETE_NOTES_FROMUNCATAGORISED_IN_SUBJECT_AD_EXPIRATION = 'DELETE_NOTES_FROMUNCATAGORISED_IN_SUBJECT_AD_EXPIRATION'







